version: '3'

networks:
  fooder_test:
    driver: bridge

services:
  database:
    restart: unless-stopped
    image: postgres
    networks:
    - fooder_test
    env_file:
      - .env.test

  api:
    restart: unless-stopped
    image: api
    build:
      dockerfile: Dockerfile
      context: .
    networks:
    - fooder_test
    env_file:
      - .env.test
    volumes:
      - ./fooder:/opt/fooder/fooder
    ports:
      - "8000:8000"
    command: "uvicorn fooder.app:app --host 0.0.0.0 --port 8000 --reload"
