version: '3'

networks:
  fooder:
    driver: bridge

services:
  database:
    restart: unless-stopped
    image: postgres
    networks:
    - fooder
    env_file:
      - .env

  api:
    restart: unless-stopped
    image: registry.domandoman.xyz/fooder/api
    build:
      dockerfile: Dockerfile
      context: .
    networks:
    - fooder
    env_file:
      - .env
    volumes:
      - ./fooder:/opt/fooder/fooder
    ports:
      - "8000:8000"
    command: "uvicorn fooder.app:app --host 0.0.0.0 --port 8000 --reload"
